name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config \
          libgtk-4-dev libadwaita-1-dev \
          libvte-2.91-gtk4-dev \
          librsvg2-common libgdk-pixbuf-2.0-dev \
          libglib2.0-dev

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
